# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-25 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commented_at', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('content', models.TextField(max_length=250)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Dweet',
            fields=[
                ('dweeted_at', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=250)),
                ('user_id', models.IntegerField(verbose_name='posted by')),
            ],
            options={
                'db_table': 'dweets',
            },
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('followed_by', models.IntegerField()),
                ('followed_to', models.IntegerField()),
            ],
            options={
                'db_table': 'follow_user',
            },
        ),
        migrations.CreateModel(
            name='LikeDweet',
            fields=[
                ('liked_at', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('dweet_id', models.OneToOneField(db_column='dweet_id', on_delete=django.db.models.deletion.CASCADE, to='dweet.Dweet')),
            ],
            options={
                'db_table': 'like_dweet',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='dweet_id',
            field=models.OneToOneField(db_column='dweet_id', on_delete=django.db.models.deletion.CASCADE, to='dweet.Dweet'),
        ),
    ]
