# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-25 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='dweet',
            name='content',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='dweet',
            name='dweeted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='likedweet',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
