# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-25 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dweet', '0003_auto_20170825_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='commented by'),
        ),
        migrations.AlterField(
            model_name='dweet',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='posted by'),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='followed_by',
            field=models.ForeignKey(db_column='followed_by', on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='followed_to',
            field=models.ForeignKey(db_column='followed_to', on_delete=django.db.models.deletion.CASCADE, related_name='followed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likedweet',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='liked by'),
        ),
    ]
